-- AlterTable
ALTER TABLE "CompanyCollection" ADD COLUMN     "conduct_score" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "debt_score" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "etr_score" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "margin_score" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "ownership_score" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "persistence_multiplier" DOUBLE PRECISION NOT NULL DEFAULT 1.0,
ADD COLUMN     "rp_haven_score" DOUBLE PRECISION NOT NULL DEFAULT 0;
